name: Update Release Build

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build_addon:
        runs-on: ubuntu-latest
        steps:
        - name: steam-workshop-upload
          uses: weilbyte/steam-workshop-upload@v1
          with: 
            appid: 294100 # Game's Steam App ID
            itemid: 3228450867 # Your mod's Steam Workshop ID
            path: '[LFS] Genes Expanded - Blood' # Path to your mod's folder from repository root
        env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password