name: Update Release Build

on:
    push:
        tags:
            - '*.*.*'

jobs:
    build_addon:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up SteamCMD
          run: |
            sudo apt-get update
            sudo apt-get install -y steamcmd
            sudo ln -s /usr/games/steamcmd steamcmd

        - name: Decode Steam Config
          env:
            STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIGVDF }}
          run: |
            echo "$STEAM_CONFIG_VDF" | base64 --decode > ~/.steam/config/config.vdf

        - name: Update Workshop Item
          run: |
            steamcmd +workshop_build_item workshop.vdf +quit